// log in 
POST https://localhost:7176/auth/login
Content-Type: application/json

{ "UserName" : "bobby", "Password" : "ilikecats" }

###

POST https://localhost:7176/auth/login
Content-Type: application/json

{ "UserName" : "kevin", "Password" : "jefffff" }

###

GET https://localhost:7176/auth/mustbeadmin
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI5MzE4ZDI0Yi02N2M5LTQ5NDUtYTI1OS00ZWJmNDg5Mzk0MzYiLCJpYXQiOiIwNi0wNC0yMDIzIDExOjQwOjIwIiwiVXNlcm5hbWUiOiJib2JieSIsIlBhc3N3b3JkIjoiaWxpa2VjYXRzIiwiUm9sZSI6IkFkbWluIiwiSWQiOiIxIiwiZXhwIjoxNjgwNzg0ODIwLCJpc3MiOiJKV1RBdXRoZW50aWNhdGlvblNlcnZlciIsImF1ZCI6IkpXVFNlcnZpY2VCbGF6b3JXYXNtQ2xpZW50In0.b5emisZ0-vPkmmwHjwxRDI_oRTngjlg9K7Rhjq5WjmQirAdIUUrimxRHtU2lIzTV3AuWwQvL-6O_hXYahpaTeg

###

GET https://localhost:7176/auth/mustbeadmin
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiJjYmU2MTE1Yi02YzExLTQ3ZjctOGJiYi1hNjkzNTkxN2VkMGUiLCJpYXQiOiIwNi0wNC0yMDIzIDExOjUxOjA5IiwiVXNlcm5hbWUiOiJrZXZpbiIsIlBhc3N3b3JkIjoiamVmZmZmZiIsIlJvbGUiOiJVc2VyIiwiSWQiOiIyIiwiZXhwIjoxNjgwNzg1NDY5LCJpc3MiOiJKV1RBdXRoZW50aWNhdGlvblNlcnZlciIsImF1ZCI6IkpXVFNlcnZpY2VCbGF6b3JXYXNtQ2xpZW50In0.-LERvRAyLI0Mac_S1C1V11VEyZGFfEpsP0C2uUyAGu6wQJ9o9XYw_CdXP4jUsXsD33PHPgcyDzGw-HSr4rusrg

###

GET https://localhost:7176/auth/manualcheck
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiJjYmU2MTE1Yi02YzExLTQ3ZjctOGJiYi1hNjkzNTkxN2VkMGUiLCJpYXQiOiIwNi0wNC0yMDIzIDExOjUxOjA5IiwiVXNlcm5hbWUiOiJrZXZpbiIsIlBhc3N3b3JkIjoiamVmZmZmZiIsIlJvbGUiOiJVc2VyIiwiSWQiOiIyIiwiZXhwIjoxNjgwNzg1NDY5LCJpc3MiOiJKV1RBdXRoZW50aWNhdGlvblNlcnZlciIsImF1ZCI6IkpXVFNlcnZpY2VCbGF6b3JXYXNtQ2xpZW50In0.-LERvRAyLI0Mac_S1C1V11VEyZGFfEpsP0C2uUyAGu6wQJ9o9XYw_CdXP4jUsXsD33PHPgcyDzGw-HSr4rusrg
